<html>
 <head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta http-equiv="Content-Style-Type" content="text/css" />
  <meta name="generator" content="Aspose.Words for .NET 15.1.0.0" />
  <title>文化部艺术发展中心</title>
 </head>
 <body>
  <div>
   <p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:14pt">&nbsp;</span></p>
   <p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:宋体; font-size:14pt; font-weight:normal">文化部艺术</span><span style="font-family:宋体; font-size:14pt; font-weight:normal">发展</span><span style="font-family:宋体; font-size:14pt; font-weight:normal">中心</span></p>
   <p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:22pt; font-weight:bold; letter-spacing:2.5pt">美术</span><span style="font-family:黑体; font-size:22pt; font-weight:bold; letter-spacing:2.5pt">考级考生报名</span><span style="font-family:黑体; font-size:22pt; font-weight:bold; letter-spacing:2.5pt">表</span></p>
   <p style="font-size:12pt; line-height:150%; margin:15.6pt 0pt 0pt; orphans:0; text-align:justify; widows:0"><span style="font-family:仿宋; font-size:12pt; font-weight:bold">&nbsp;&nbsp; </span><span style="font-family:仿宋; font-size:12pt; font-weight:bold">报名时间</span><span style="font-family:仿宋; font-size:12pt; font-weight:bold">：</span><span style="font-family:仿宋; font-size:10.5pt; font-weight:normal">${examTime} &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="font-family:仿宋; font-size:10.5pt; font-weight:normal"> </span><span style="font-family:仿宋; font-size:10.5pt; font-weight:normal">&nbsp;</span><span style="font-family:仿宋; font-size:10.5pt; font-weight:normal"> </span><span style="font-family:仿宋; font-size:10.5pt; font-weight:normal">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="font-family:仿宋; font-size:12pt; font-weight:bold">考生编号：</span><span style="font-family:仿宋; font-size:12pt; font-weight:bold"> </span></p>
   <div style="text-align:center">
    <table cellspacing="0" cellpadding="0" style="border-collapse:collapse; margin:0 auto; width:468.8pt">
     <tbody>
      <tr style="height:31.2pt">
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:1pt; border-left-color:#000000; border-left-style:solid; border-left-width:1pt; border-right-color:#000000; border-right-style:solid; border-right-width:1pt; border-top-color:#000000; border-top-style:solid; border-top-width:1pt; padding-left:4.9pt; padding-right:4.9pt; vertical-align:middle; width:59.2pt"><p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:10.5pt">姓　　名</span></p></td>
       <td colspan="4" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:1pt; border-left-color:#000000; border-left-style:solid; border-left-width:1pt; border-right-color:#000000; border-right-style:solid; border-right-width:1pt; border-top-color:#000000; border-top-style:solid; border-top-width:1pt; padding-left:4.9pt; padding-right:4.9pt; vertical-align:middle; width:161.3pt"><p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:10.5pt">${studentName}</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:1pt; border-left-color:#000000; border-left-style:solid; border-left-width:1pt; border-right-color:#000000; border-right-style:solid; border-right-width:1pt; border-top-color:#000000; border-top-style:solid; border-top-width:1pt; padding-left:4.9pt; padding-right:4.9pt; vertical-align:middle; width:43.2pt"><p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:10.5pt">性</span><span style="font-family:黑体; font-size:10.5pt">&nbsp;&nbsp;&nbsp; </span><span style="font-family:黑体; font-size:10.5pt">别</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:1pt; border-left-color:#000000; border-left-style:solid; border-left-width:1pt; border-right-color:#000000; border-right-style:solid; border-right-width:1pt; border-top-color:#000000; border-top-style:solid; border-top-width:1pt; padding-left:4.9pt; padding-right:4.9pt; vertical-align:middle; width:52.2pt"><p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:10.5pt">${gender}</span></p></td>
       <td rowspan="4" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:1pt; border-left-color:#000000; border-left-style:solid; border-left-width:1pt; border-right-color:#000000; border-right-style:solid; border-right-width:1pt; border-top-color:#000000; border-top-style:solid; border-top-width:1pt; padding-left:4.9pt; padding-right:4.9pt; vertical-align:middle; width:97.9pt"><p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:10.5pt">照</span></p><p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:10.5pt">&nbsp;</span></p><p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:10.5pt">片</span></p><p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:10.5pt">&nbsp;</span></p><p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:10.5pt">（</span><span style="font-family:黑体; font-size:10.5pt">2吋</span><span style="font-family:黑体; font-size:10.5pt">）</span></p></td>
      </tr>
      <tr style="height:31.2pt">
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:1pt; border-left-color:#000000; border-left-style:solid; border-left-width:1pt; border-right-color:#000000; border-right-style:solid; border-right-width:1pt; border-top-color:#000000; border-top-style:solid; border-top-width:1pt; padding-left:4.9pt; padding-right:4.9pt; vertical-align:middle; width:59.2pt"><p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:10.5pt">姓名拼音</span></p></td>
       <td colspan="4" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:1pt; border-left-color:#000000; border-left-style:solid; border-left-width:1pt; border-right-color:#000000; border-right-style:solid; border-right-width:1pt; border-top-color:#000000; border-top-style:solid; border-top-width:1pt; padding-left:4.9pt; padding-right:4.9pt; vertical-align:middle; width:161.3pt"><p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:10.5pt">&nbsp;</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:1pt; border-left-color:#000000; border-left-style:solid; border-left-width:1pt; border-right-color:#000000; border-right-style:solid; border-right-width:1pt; border-top-color:#000000; border-top-style:solid; border-top-width:1pt; padding-left:4.9pt; padding-right:4.9pt; vertical-align:middle; width:43.2pt"><p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:10.5pt">民</span><span style="font-family:黑体; font-size:10.5pt">&nbsp;&nbsp;&nbsp; </span><span style="font-family:黑体; font-size:10.5pt">族</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:1pt; border-left-color:#000000; border-left-style:solid; border-left-width:1pt; border-right-color:#000000; border-right-style:solid; border-right-width:1pt; border-top-color:#000000; border-top-style:solid; border-top-width:1pt; padding-left:4.9pt; padding-right:4.9pt; vertical-align:middle; width:52.2pt"><p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:10.5pt">${nation}</span></p></td>
      </tr>
      <tr style="height:31.2pt">
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:1pt; border-left-color:#000000; border-left-style:solid; border-left-width:1pt; border-right-color:#000000; border-right-style:solid; border-right-width:1pt; border-top-color:#000000; border-top-style:solid; border-top-width:1pt; padding-left:4.9pt; padding-right:4.9pt; vertical-align:middle; width:59.2pt"><p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:10.5pt">出生日期</span></p></td>
       <td colspan="4" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:1pt; border-left-color:#000000; border-left-style:solid; border-left-width:1pt; border-right-color:#000000; border-right-style:solid; border-right-width:1pt; border-top-color:#000000; border-top-style:solid; border-top-width:1pt; padding-left:4.9pt; padding-right:4.9pt; vertical-align:middle; width:161.3pt"><p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:10.5pt">${birthday}</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:1pt; border-left-color:#000000; border-left-style:solid; border-left-width:1pt; border-right-color:#000000; border-right-style:solid; border-right-width:1pt; border-top-color:#000000; border-top-style:solid; border-top-width:1pt; padding-left:4.9pt; padding-right:4.9pt; vertical-align:middle; width:43.2pt"><p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:10.5pt">国</span><span style="font-family:黑体; font-size:10.5pt">&nbsp;&nbsp;&nbsp; </span><span style="font-family:黑体; font-size:10.5pt">籍</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:1pt; border-left-color:#000000; border-left-style:solid; border-left-width:1pt; border-right-color:#000000; border-right-style:solid; border-right-width:1pt; border-top-color:#000000; border-top-style:solid; border-top-width:1pt; padding-left:4.9pt; padding-right:4.9pt; vertical-align:middle; width:52.2pt"><p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:10.5pt">${state}</span></p></td>
      </tr>
      <tr style="height:31.2pt">
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:1pt; border-left-color:#000000; border-left-style:solid; border-left-width:1pt; border-right-color:#000000; border-right-style:solid; border-right-width:1pt; border-top-color:#000000; border-top-style:solid; border-top-width:1pt; padding-left:4.9pt; padding-right:4.9pt; vertical-align:middle; width:59.2pt"><p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:10.5pt">考生所在地</span></p></td>
       <td colspan="6" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:1pt; border-left-color:#000000; border-left-style:solid; border-left-width:1pt; border-right-color:#000000; border-right-style:solid; border-right-width:1pt; border-top-color:#000000; border-top-style:solid; border-top-width:1pt; padding-left:4.9pt; padding-right:4.9pt; vertical-align:middle; width:278.3pt"><p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:10.5pt">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="font-family:黑体; font-size:10.5pt">省(自治区/直辖市)　</span><span style="font-family:黑体; font-size:10.5pt">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="font-family:黑体; font-size:10.5pt">市/县</span></p></td>
      </tr>
      <tr style="height:31.2pt">
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:1pt; border-left-color:#000000; border-left-style:solid; border-left-width:1pt; border-right-color:#000000; border-right-style:solid; border-right-width:1pt; border-top-color:#000000; border-top-style:solid; border-top-width:1pt; padding-left:4.9pt; padding-right:4.9pt; vertical-align:middle; width:59.2pt"><p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:10.5pt">申报专业</span></p></td>
       <td colspan="3" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:1pt; border-left-color:#000000; border-left-style:solid; border-left-width:1pt; border-right-color:#000000; border-right-style:solid; border-right-width:1pt; border-top-color:#000000; border-top-style:solid; border-top-width:1pt; padding-left:4.9pt; padding-right:4.9pt; vertical-align:middle; width:98.3pt"><p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:10.5pt">${subjectName}</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:1pt; border-left-color:#000000; border-left-style:solid; border-left-width:1pt; border-right-color:#000000; border-right-style:solid; border-right-width:1pt; border-top-color:#000000; border-top-style:solid; border-top-width:1pt; padding-left:4.9pt; padding-right:4.9pt; vertical-align:middle; width:52.2pt"><p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:10.5pt">申报级别</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:1pt; border-left-color:#000000; border-left-style:solid; border-left-width:1pt; border-right-color:#000000; border-right-style:solid; border-right-width:1pt; border-top-color:#000000; border-top-style:solid; border-top-width:1pt; padding-left:4.9pt; padding-right:4.9pt; vertical-align:middle; width:43.2pt"><p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:10.5pt">${rank}</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:1pt; border-left-color:#000000; border-left-style:solid; border-left-width:1pt; border-right-color:#000000; border-right-style:solid; border-right-width:1pt; border-top-color:#000000; border-top-style:solid; border-top-width:1pt; padding-left:4.9pt; padding-right:4.9pt; vertical-align:middle; width:52.2pt"><p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:10.5pt">考级机构</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:1pt; border-left-color:#000000; border-left-style:solid; border-left-width:1pt; border-right-color:#000000; border-right-style:solid; border-right-width:1pt; border-top-color:#000000; border-top-style:solid; border-top-width:1pt; padding-left:4.9pt; padding-right:4.9pt; vertical-align:middle; width:97.9pt"><p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:10.5pt">文化部艺术发展中心</span></p></td>
      </tr>
      <tr style="height:31.2pt">
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:1pt; border-left-color:#000000; border-left-style:solid; border-left-width:1pt; border-right-color:#000000; border-right-style:solid; border-right-width:1pt; border-top-color:#000000; border-top-style:solid; border-top-width:1pt; padding-left:4.9pt; padding-right:4.9pt; vertical-align:middle; width:59.2pt"><p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:10.5pt">申报专业</span></p><p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:10.5pt; letter-spacing:-0.5pt">已过最高级别</span></p></td>
       <td colspan="2" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:1pt; border-left-color:#000000; border-left-style:solid; border-left-width:1pt; border-right-color:#000000; border-right-style:solid; border-right-width:1pt; border-top-color:#000000; border-top-style:solid; border-top-width:1pt; padding-left:4.9pt; padding-right:4.9pt; vertical-align:middle; width:41.75pt"><p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:10.5pt">&nbsp;</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:1pt; border-left-color:#000000; border-left-style:solid; border-left-width:1pt; border-right-color:#000000; border-right-style:solid; border-right-width:1pt; border-top-color:#000000; border-top-style:solid; border-top-width:1pt; padding-left:4.9pt; padding-right:4.9pt; vertical-align:middle; width:45.75pt"><p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:10.5pt">证书编号</span></p></td>
       <td colspan="2" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:1pt; border-left-color:#000000; border-left-style:solid; border-left-width:1pt; border-right-color:#000000; border-right-style:solid; border-right-width:1pt; border-top-color:#000000; border-top-style:solid; border-top-width:1pt; padding-left:4.9pt; padding-right:4.9pt; vertical-align:middle; width:106.2pt"><p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:10.5pt">&nbsp;</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:1pt; border-left-color:#000000; border-left-style:solid; border-left-width:1pt; border-right-color:#000000; border-right-style:solid; border-right-width:1pt; border-top-color:#000000; border-top-style:solid; border-top-width:1pt; padding-left:4.9pt; padding-right:4.9pt; vertical-align:middle; width:52.2pt"><p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:10.5pt">发证机构</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:1pt; border-left-color:#000000; border-left-style:solid; border-left-width:1pt; border-right-color:#000000; border-right-style:solid; border-right-width:1pt; border-top-color:#000000; border-top-style:solid; border-top-width:1pt; padding-left:4.9pt; padding-right:4.9pt; vertical-align:middle; width:97.9pt"><p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:10.5pt">&nbsp;</span></p></td>
      </tr>
      <tr style="height:31.2pt">
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:1pt; border-left-color:#000000; border-left-style:solid; border-left-width:1pt; border-right-color:#000000; border-right-style:solid; border-right-width:1pt; border-top-color:#000000; border-top-style:solid; border-top-width:1pt; padding-left:4.9pt; padding-right:4.9pt; vertical-align:middle; width:59.2pt"><p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:10.5pt">承办单位</span></p></td>
       <td colspan="5" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:1pt; border-left-color:#000000; border-left-style:solid; border-left-width:1pt; border-right-color:#000000; border-right-style:solid; border-right-width:1pt; border-top-color:#000000; border-top-style:solid; border-top-width:1pt; padding-left:4.9pt; padding-right:4.9pt; vertical-align:middle; width:215.3pt"><p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:10.5pt">${schoolName}</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:1pt; border-left-color:#000000; border-left-style:solid; border-left-width:1pt; border-right-color:#000000; border-right-style:solid; border-right-width:1pt; border-top-color:#000000; border-top-style:solid; border-top-width:1pt; padding-left:4.9pt; padding-right:4.9pt; vertical-align:middle; width:52.2pt"><p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:10.5pt">联系电话</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:1pt; border-left-color:#000000; border-left-style:solid; border-left-width:1pt; border-right-color:#000000; border-right-style:solid; border-right-width:1pt; border-top-color:#000000; border-top-style:solid; border-top-width:1pt; padding-left:4.9pt; padding-right:4.9pt; vertical-align:middle; width:97.9pt"><p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:10.5pt">&nbsp;</span></p></td>
      </tr>
      <tr style="height:31.2pt">
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:1pt; border-left-color:#000000; border-left-style:solid; border-left-width:1pt; border-right-color:#000000; border-right-style:solid; border-right-width:1pt; border-top-color:#000000; border-top-style:solid; border-top-width:1pt; padding-left:4.9pt; padding-right:4.9pt; vertical-align:middle; width:59.2pt"><p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:10.5pt; letter-spacing:-0.8pt">考生联系人</span></p></td>
       <td colspan="3" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:1pt; border-left-color:#000000; border-left-style:solid; border-left-width:1pt; border-right-color:#000000; border-right-style:solid; border-right-width:1pt; border-top-color:#000000; border-top-style:solid; border-top-width:1pt; padding-left:4.9pt; padding-right:4.9pt; vertical-align:middle; width:98.3pt"><p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:10.5pt">&nbsp;</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:1pt; border-left-color:#000000; border-left-style:solid; border-left-width:1pt; border-right-color:#000000; border-right-style:solid; border-right-width:1pt; border-top-color:#000000; border-top-style:solid; border-top-width:1pt; padding-left:4.9pt; padding-right:4.9pt; vertical-align:middle; width:52.2pt"><p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:10.5pt; letter-spacing:-0.5pt">与考生关系</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:1pt; border-left-color:#000000; border-left-style:solid; border-left-width:1pt; border-right-color:#000000; border-right-style:solid; border-right-width:1pt; border-top-color:#000000; border-top-style:solid; border-top-width:1pt; padding-left:4.9pt; padding-right:4.9pt; vertical-align:middle; width:43.2pt"><p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:10.5pt">&nbsp;</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:1pt; border-left-color:#000000; border-left-style:solid; border-left-width:1pt; border-right-color:#000000; border-right-style:solid; border-right-width:1pt; border-top-color:#000000; border-top-style:solid; border-top-width:1pt; padding-left:4.9pt; padding-right:4.9pt; vertical-align:middle; width:52.2pt"><p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:10.5pt">联系电话</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:1pt; border-left-color:#000000; border-left-style:solid; border-left-width:1pt; border-right-color:#000000; border-right-style:solid; border-right-width:1pt; border-top-color:#000000; border-top-style:solid; border-top-width:1pt; padding-left:4.9pt; padding-right:4.9pt; vertical-align:middle; width:97.9pt"><p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:10.5pt">&nbsp;</span></p></td>
      </tr>
      <tr style="height:31.2pt">
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:1pt; border-left-color:#000000; border-left-style:solid; border-left-width:1pt; border-right-color:#000000; border-right-style:solid; border-right-width:1pt; border-top-color:#000000; border-top-style:solid; border-top-width:1pt; padding-left:4.9pt; padding-right:4.9pt; vertical-align:middle; width:59.2pt"><p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:10.5pt">通讯地址</span></p></td>
       <td colspan="5" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:1pt; border-left-color:#000000; border-left-style:solid; border-left-width:1pt; border-right-color:#000000; border-right-style:solid; border-right-width:1pt; border-top-color:#000000; border-top-style:solid; border-top-width:1pt; padding-left:4.9pt; padding-right:4.9pt; vertical-align:middle; width:215.3pt"><p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:10.5pt">&nbsp;</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:1pt; border-left-color:#000000; border-left-style:solid; border-left-width:1pt; border-right-color:#000000; border-right-style:solid; border-right-width:1pt; border-top-color:#000000; border-top-style:solid; border-top-width:1pt; padding-left:4.9pt; padding-right:4.9pt; vertical-align:middle; width:52.2pt"><p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:10.5pt">邮政编码</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:1pt; border-left-color:#000000; border-left-style:solid; border-left-width:1pt; border-right-color:#000000; border-right-style:solid; border-right-width:1pt; border-top-color:#000000; border-top-style:solid; border-top-width:1pt; padding-left:4.9pt; padding-right:4.9pt; vertical-align:middle; width:97.9pt"><p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:10.5pt">&nbsp;</span></p></td>
      </tr>
      <tr style="height:81.45pt">
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:1pt; border-left-color:#000000; border-left-style:solid; border-left-width:1pt; border-right-color:#000000; border-right-style:solid; border-right-width:1pt; border-top-color:#000000; border-top-style:solid; border-top-width:1pt; padding-left:4.9pt; padding-right:4.9pt; vertical-align:middle; width:59.2pt"><p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:10.5pt">备注一</span></p></td>
       <td colspan="7" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:1pt; border-left-color:#000000; border-left-style:solid; border-left-width:1pt; border-right-color:#000000; border-right-style:solid; border-right-width:1pt; border-top-color:#000000; border-top-style:solid; border-top-width:1pt; padding-left:4.9pt; padding-right:4.9pt; vertical-align:middle; width:387pt"><p style="line-height:18.7pt; margin:0pt; orphans:0; text-align:justify; widows:0"><span style="font-family:楷体; font-size:10.5pt">1.以上各项内容对考试结果以及证书制作非常重要，请完整、准确、清晰填写或打印有关事项；</span></p><p style="line-height:18.7pt; margin:0pt; orphans:0; text-align:justify; widows:0"><span style="font-family:楷体; font-size:10.5pt">2.</span><span style="font-family:楷体; font-size:10.5pt">申报专业</span><span style="font-family:楷体; font-size:10.5pt">已过其他机构最高级别证书复印件附在此表后；</span></p><p style="line-height:18.7pt; margin:0pt; orphans:0; text-align:justify; widows:0"><span style="font-family:楷体; font-size:10.5pt">3.考生编号由承办单位统一编写。</span></p><p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:10.5pt">&nbsp;</span></p></td>
      </tr>
      <tr style="height:203.25pt">
       <td rowspan="2" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:1pt; border-left-color:#000000; border-left-style:solid; border-left-width:1pt; border-right-color:#000000; border-right-style:solid; border-right-width:1pt; border-top-color:#000000; border-top-style:solid; border-top-width:1pt; padding-left:4.9pt; padding-right:4.9pt; vertical-align:middle; width:59.2pt"><p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:10.5pt">评审</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:1pt; border-left-color:#000000; border-left-style:solid; border-left-width:1pt; border-right-color:#000000; border-right-style:solid; border-right-width:1pt; border-top-color:#000000; border-top-style:solid; border-top-width:1pt; padding-left:4.9pt; padding-right:4.9pt; vertical-align:middle; width:31pt"><p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:10.5pt">评语</span></p></td>
       <td colspan="6" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:1pt; border-left-color:#000000; border-left-style:solid; border-left-width:1pt; border-right-color:#000000; border-right-style:solid; border-right-width:1pt; border-top-color:#000000; border-top-style:solid; border-top-width:1pt; padding-left:4.9pt; padding-right:4.9pt; vertical-align:middle; width:345.2pt"><p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:10.5pt">&nbsp;</span></p><p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:10.5pt">&nbsp;</span></p><p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:10.5pt">&nbsp;</span></p><p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:10.5pt">&nbsp;</span></p><p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:10.5pt">&nbsp;</span></p><p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:10.5pt">&nbsp;</span></p><p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:10.5pt">&nbsp;</span></p><p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:10.5pt">&nbsp;</span></p><p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:10.5pt">&nbsp;</span></p><p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:10.5pt">&nbsp;</span></p><p style="margin:0pt; orphans:0; text-align:justify; widows:0"><span style="font-family:黑体; font-size:10.5pt">&nbsp;</span></p></td>
      </tr>
      <tr style="height:35.9pt">
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:1pt; border-left-color:#000000; border-left-style:solid; border-left-width:1pt; border-right-color:#000000; border-right-style:solid; border-right-width:1pt; border-top-color:#000000; border-top-style:solid; border-top-width:1pt; padding-left:4.9pt; padding-right:4.9pt; vertical-align:middle; width:31pt"><p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:10.5pt">结果</span></p></td>
       <td colspan="4" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:1pt; border-left-color:#000000; border-left-style:solid; border-left-width:1pt; border-right-color:#000000; border-right-style:solid; border-right-width:1pt; border-top-color:#000000; border-top-style:solid; border-top-width:1pt; padding-left:4.9pt; padding-right:4.9pt; vertical-align:middle; width:173.5pt"><p style="margin:0pt; orphans:0; text-align:justify; widows:0"><span style="font-family:黑体; font-size:10.5pt">&nbsp;</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:1pt; border-left-color:#000000; border-left-style:solid; border-left-width:1pt; border-right-color:#000000; border-right-style:solid; border-right-width:1pt; border-top-color:#000000; border-top-style:solid; border-top-width:1pt; padding-left:4.9pt; padding-right:4.9pt; vertical-align:middle; width:52.2pt"><p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:10.5pt">考官签字</span></p></td>
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:1pt; border-left-color:#000000; border-left-style:solid; border-left-width:1pt; border-right-color:#000000; border-right-style:solid; border-right-width:1pt; border-top-color:#000000; border-top-style:solid; border-top-width:1pt; padding-left:4.9pt; padding-right:4.9pt; vertical-align:middle; width:97.9pt"><p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:10.5pt">&nbsp;</span></p></td>
      </tr>
      <tr style="height:49.2pt">
       <td style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:1pt; border-left-color:#000000; border-left-style:solid; border-left-width:1pt; border-right-color:#000000; border-right-style:solid; border-right-width:1pt; border-top-color:#000000; border-top-style:solid; border-top-width:1pt; padding-left:4.9pt; padding-right:4.9pt; vertical-align:middle; width:59.2pt"><p style="margin:0pt; orphans:0; text-align:center; widows:0"><span style="font-family:黑体; font-size:10.5pt">备注</span><span style="font-family:黑体; font-size:10.5pt">二</span></p></td>
       <td colspan="7" style="border-bottom-color:#000000; border-bottom-style:solid; border-bottom-width:1pt; border-left-color:#000000; border-left-style:solid; border-left-width:1pt; border-right-color:#000000; border-right-style:solid; border-right-width:1pt; border-top-color:#000000; border-top-style:solid; border-top-width:1pt; padding-left:4.9pt; padding-right:4.9pt; vertical-align:middle; width:387pt"><p style="line-height:18.7pt; margin:0pt; orphans:0; text-align:justify; widows:0"><span style="font-family:楷体; font-size:10.5pt">集中统一评定考试</span><span style="font-family:楷体; font-size:10.5pt">成绩</span><span style="font-family:楷体; font-size:10.5pt">，</span><span style="font-family:楷体; font-size:10.5pt">切勿</span><span style="font-family:楷体; font-size:10.5pt">将此表</span><span style="font-family:楷体; font-size:10.5pt">与对应</span><span style="font-family:楷体; font-size:10.5pt">考级</span><span style="font-family:楷体; font-size:10.5pt">作品分离</span><span style="font-family:楷体; font-size:10.5pt">。</span></p></td>
      </tr>
      <tr style="height:0pt">
       <td style="width:70pt; border:none"></td>
       <td style="width:41.8pt; border:none"></td>
       <td style="width:10.75pt; border:none"></td>
       <td style="width:56.55pt; border:none"></td>
       <td style="width:63pt; border:none"></td>
       <td style="width:54pt; border:none"></td>
       <td style="width:63pt; border:none"></td>
       <td style="width:108.7pt; border:none"></td>
      </tr>
     </tbody>
    </table>
   </div>
   <img src="37ac232e-c785-4ecb-b01a-4d79e4c3f85e.001.png" width="564" height="34" alt="" style="-aw-left-pos:0pt; -aw-rel-hpos:column; -aw-rel-vpos:paragraph; -aw-top-pos:343.2pt; -aw-wrap-type:none; margin-left:0pt; margin-top:343.2pt; position:absolute; z-index:-65535" />
   <p style="margin:0pt; orphans:0; text-align:justify; widows:0"><span style="font-family:黑体; font-size:9pt; font-weight:bold; letter-spacing:4pt">&nbsp;</span></p>
  </div>
  <div class="cnzz" style="display: none;"> 
  </div>
 </body>
</html>